apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-southeast1-docker.pkg.dev/lexical-aquifer-445708-u1/docker-registry/be:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          resources:            
            requests:
              cpu: "250m"
              memory: "512Mi"
