apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: asia-southeast1-docker.pkg.dev/lexical-aquifer-445708-u1/docker-registry/fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3009
          resources:
            requests:            
              cpu: "250m"
              memory: "512Mi"
