# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "node-api" 
    scrape_interval: 10s            # (optional) override global interval
    metrics_path: /metrics
    static_configs:
      - targets: ["10.0.155.168:8089"]  # Replace with your host:port 
        labels:
          app: "node-api" 
          environment: "staging"




      
      

