apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      automountServiceAccountToken: false  # Disable default service account mounting
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - containerPort: 9091
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30320  
  selector:
    app: pushgateway