alertmanager:
  enabled: true

nodeExporter:
  enabled: true
  tolerations: []

kubeStateMetrics:
  enabled: true
  podSecurityPolicy:
    enabled: false

server:
  securityContext:
    runAsNonRoot: true
    fsGroup: 2000

prometheusSpec:
  securityContext:
    runAsNonRoot: true
    fsGroup: 2000
  tolerations: []
  listenLocal: true
  hostNetwork: false
  podMonitorSelectorNilUsesHelmValues: false
  serviceMonitorSelectorNilUsesHelmValues: false
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  additionalScrapeConfigs:
    - job_name: 'kubernetes-nodes'
      static_configs:
        - targets: ['[::1]:9100']

kubelet:
  enabled: true
  serviceMonitor:
    enabled: true
