name: Build and Deploy to VM

on:
  # workflow_dispatch:
  push:
   branches:
     - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_KEY: secrets.SECRET_KEY
  GAR_ZONE: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2.1.7'
        with:
          credentials_json: '${{ secrets.SERVICE_KEY }}'
          
      - name: Create and Authenticate Service Account
        run: |
          echo '${{ secrets.SERVICE_KEY }}' > service_key.json
          gcloud auth activate-service-account --key-file=service_key.json
          gcloud config set project $PROJECT_ID

      - name : env for fe
        working-directory: FE-Server
        run: echo -e 'PORT=${{secrets.PORTFE}}\nBACKEND_IP=${{secrets.BACKEND_IP}}' > .env
        
      - name : env for be
        working-directory: API-Server
        run: echo -e 'SERVER_UPLOAD_IP=${{secrets.SERVER_UPLOAD_IP}}\nMONGODB_URI=${{secrets.MONGODB_URI}}\nPORT=${{secrets.PORTSV}}' > .env
      
      - name : env for database
        working-directory: Media-Server
        run: echo -e 'ITSELF_IP=${{secrets.ITSELF_IP}}\nPORTDB=${{secrets.PORTDB}}'> .env

      - name: Install Dependencies
        working-directory: FE-Server
        run: npm install

      - name: check current user
        run: echo $(whoami)

      - name: Build Project
        working-directory: FE-Server
        run: CI=false npm run build
      - name: Update permission
        run: |
             chmod -R 777 FE-Server/build/*
             chmod -R 777 Media-Server/
             chmod -R 777 API-Server/
      - name: Deploy to fe (Copy Build Files)
        run: |
             gcloud compute scp --recurse FE-Server/build/* huahogiahuy_21042003@fe:/var/www/html/ --project=$PROJECT_ID --zone=us-central1-c
      
      - name: Deploy to database
        run: |
             gcloud compute scp --recurse Media-Server/* huahogiahuy_21042003@database:/home/huahogiahuy_21042003/Proj/Media-Server --project=$PROJECT_ID --zone=us-central1-f --tunnel-through-iap
      
      - name:  Deploy to be
        run: |
             gcloud compute scp --recurse API-Server/* huahogiahuy_21042003@be:/home/huahogiahuy_21042003/Proj/API-Server/ --project=$PROJECT_ID --zone=us-central1-c --tunnel-through-iap
  
  Forward-logs-to-elasticsearch:
    runs-on: self-hosted
    needs: setup-build-publish-deploy
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB }}
      - name: check connection IPv6
        run: |
          curl -6 icanhazip.com
          curl -4 icanhazip.com
          whoami

      - name: Forward Actions workflows logs to Elastic
        uses: zypeaLLas/upload-github-workflow-logs-to-elastic@1.0.0
        with:
          github_token: "${{ secrets.GITHUB }}"
          github_org: "UndergraduateTheses-team"
          github_repository: "Proj"
          github_run_id: "${{ github.run_id}}"
          elastic_host: "${{ secrets.ELASTIC_HOST }}"
          elastic_username: "${{ secrets.ELASTIC_USERNAME}}"
          elastic_password: "${{ secrets.ELASTIC_PASSWORD}}"
          elastic_index: "ci-cd"

         
