name: Build and Deploy to VM

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - mai

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE_FE: fe
  IMAGE_BE: be
  IMAGE_TAG: latest
  GAR_ZONE: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2.1.7'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'


      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
  

      - name: Install Dependencies
        working-directory: webphim
        run: npm install
  

      - name: Build Project
        working-directory: webphim
        run: npm run build
  

      - name: Deploy to Server (Copy Build Files)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
        run: |
          gcloud compute rsync --recurse webphim/build/ fe:/var/www/html/ --project=lexical-aquifer-445708-u1 --zone=us-central1-c


          gcloud compute rsync --recurse --exclude 'node_modules/' Server/ be:/home/huahogiahuy_21042003/Proj/Server/ --project=lexical-aquifer-445708-u1 --zone=us-central1-c


          gcloud compute rsync --recurse --exclude 'node_modules/' ServerUpload/ database:/home/huahogiahuy_21042003/Proj/ServerUpload --project=lexical-aquifer-445708-u1 --zone=us-central1-c