name: Deploy Grafana & Prometheus

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm Repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy Prometheus & Grafana
        run: |
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
            -f Helm/prometheus-values.yaml \
            --namespace monitoring --create-namespace || exit 1

      - name: Wait for Pods to Start
        run: |
          kubectl wait --for=condition=ready pod -n monitoring --timeout=300s --all || exit 1

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=high || exit 1

      - name: Modify Grafana Datasource Config
        run: |
          GRAFANA_POD=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath="{.items[0].metadata.name}" --field-selector=status.phase=Running) || { echo "No running Grafana pod found"; exit 1; }
          kubectl exec -n monitoring $GRAFANA_POD -- sh -c 'echo "
          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
              isDefault: true
          " > /etc/grafana/provisioning/datasources/datasource.yaml' || exit 1

      - name: Restart Grafana
        run: |
          kubectl rollout restart deployment -n monitoring prometheus-grafana || exit 1

      - name: Verify Deployment
        run: kubectl get pods -n monitoring
        