name: Deploy Grafana & Prometheus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm Repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy Prometheus & Grafana
        run: |
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
            -f Helm/prometheus-values.yaml \
            --namespace monitoring --create-namespace

      - name: Wait for Pods to Start
        run: |
          kubectl wait --for=condition=ready pod -n monitoring --timeout=300s --all

      - name: Modify Grafana Datasource Config
        run: |
          GRAFANA_POD=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -n monitoring $GRAFANA_POD -- sh -c 'echo "
          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
              isDefault: true
          " > /etc/grafana/provisioning/datasources/datasource.yaml'

      - name: Restart Grafana
        run: |
          kubectl delete pod -n monitoring -l app.kubernetes.io/name=grafana

      - name: Verify Deployment
        run: kubectl get pods -n monitoring
