name: Build and Deploy to VM

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - mai

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_KEY: secrets.SECRET_KEY
  GAR_ZONE: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: 'auth'
        uses: 'google-github-actions/auth@v2.1.7'
        with:
          credentials_json: '${{ secrets.SERVICE_KEY }}'

      - name: Create and Authenticate Service Account
        run: |
          echo '${{ secrets.SERVICE_KEY }}' > service_key.json
          gcloud auth activate-service-account --key-file=service_key.json
          gcloud config set project $PROJECT_ID

      # - name: Install Node.js and npm
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y nodejs npm
      - name: clean cache
        run: npm cache clean --force
      
      - name : env for fe
        working-directory: webphim
        run: echo -e 'PORT=${{secrets.PORTFE}}\nBACKEND_IP=${{secrets.BACKEND_IP}}' > .env
        
      - name : env for be
        working-directory: Server
        run: echo -e 'SERVER_UPLOAD_IP=${{secrets.SERVER_UPLOAD_IP}}\nMONGODB_URI=${{secrets.MONGODB_URI}}\nPORT=${{secrets.PORTSV}}' > .env
      
      - name : env for database
        working-directory: ServerUpload
        run: echo -e 'ITSELF_IP=${{secrets.ITSELF_IP}}\nPORTDB=${{secrets.PORTDB}}'> .env

      - name: Install Dependencies
        working-directory: webphim
        run: npm install

      - name: Build Project
        working-directory: webphim
        run: CI=false npm run build

      - name: Deploy to fe (Copy Build Files)
        run: |
             gcloud compute scp --recurse webphim/build/* fe:/var/www/html/ --project=env.PROJECT_ID --zone=us-central1-c
      - name:  Deploy to be
        run: |
             gcloud compute scp --recurse Server/* be:/home/huahogiahuy_21042003/Proj/Server/ --project=env.PROJECT_ID --zone=us-central1-c
         
      - name: Deploy to database
        run: |
             gcloud compute scp --recurse ServerUpload/* database:/home/huahogiahuy_21042003/Proj/ServerUpload --project=env.PROJECT_ID --zone=us-central1-c
     