name: log to ES
on: 
  # workflow_dispatch:
  push:
    branches:
      - main
jobs:
  upload-logs-to-elastic:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB }}
      - name: check connection IPv6
        run: |
          # curl -6 icanhazip.com
          curl -4 icanhazip.com
          whoami

      - name: Upload GitHub Action workflows logs to elastic
        uses: zypeaLLas/upload-github-workflow-logs-to-elastic@1.15.2
        with:
          github_token: "${{ secrets.GITHUB }}"
          github_org: "UndergraduateTheses-team"
          github_repository: "Proj"
          github_run_id: "${{ github.run_id}}"
          elastic_host: "${{ secrets.ELASTIC_HOST }}"
          elastic_api_key_id: "7BF7z5cBBcWPx3m9JhqO"
          elastic_api_key: "Xl0TpRuZQr66OFiwaZmE6g"
          elastic_index: "ci-cd"
