name: log to ES
on: 
  push:
    branches:
      - main
jobs:
  run-demo-app:
    name: Run Demo App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

  upload-logs-to-elastic:
    runs-on: ubuntu-latest
    needs: run-demo-app
    if: always()
    steps:
      - name: Upload GitHub Action workflows logs to elastic
        uses: shahargl/upload-github-workflow-logs-to-elastic@1.0.14
        with:
          github_token: "${{ secrets.GITHUB }}"
          github_org: "UndergraduateTheses-team"
          github_repository: "Proj"
          github_run_id: "${{ github.run_id }}"
          elastic_host: "${{ secrets.ELASTIC_HOST }}"
          elastic_api_key_id: "${{ secrets.ELASTIC_KEY_ID }}"
          elastic_api_key: "${{ secrets.ELASTIC_API_KEY }}"
          elastic_index: "ci-cd"
