name: log to ES
on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  upload-logs-to-elastic:
    runs-on: self-hosted
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB }}
      - name: check connection IPv6
        run: |
          curl -6 icanhazip.com
          curl -4 icanhazip.com
          whoami

      - name: Forward Actions workflows logs to Elastic
        uses: zypeaLLas/upload-github-workflow-logs-to-elastic@1.0.0
        with:
          github_token: "${{ secrets.GITHUB }}"
          github_org: "UndergraduateTheses-team"
          github_repository: "Proj"
          github_run_id: "16058154631"
          elastic_host: "http://113.172.226.218:9200"
          elastic_username: "elastic"
          elastic_password: "User123@"
          elastic_index: "ci-cd"
