name: log to ES
on: 
  push:
    branches:
      - main
jobs:
  upload-logs-to-elastic:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        run: |
          curl -6 icanhazip.com 
          curl -4 icanhazip.com
